# Generated by Django 4.0.3 on 2022-04-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIDAS_app', '0003_alter_parameter_infos_alter_station_infos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Height in meters', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
    ]
