version: '3.9'
services:
  server:
    image: ghcr.io/heg-midas/midas:master
    restart: unless-stopped
    volumes:
      - nginx_conf:/app/docker/nginx/conf
      - static:/app/static
      - media:/app/media
      - backup:/app/backup
    ports:
      - "8000:8000"
    environment:
      - admin_username=admin
      - admin_password=pw
      - admin_email=midas@midas.ch
  static:
      image: nginx
      depends_on:
        - server
      volumes:
        - static:/var/www:ro
        - nginx_conf:/etc/nginx/conf.d
      restart: unless-stopped
  runner:
    image: ghcr.io/heg-midas/midas:master
    restart: "no"
    volumes:
      - media:/app/media
    command: bash /app/docker/jobrunner.sh
  scheduler:
    image: mcuadros/ofelia:latest
    depends_on:
      - server
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.uname.schedule: "@daily"
      ofelia.job-run.uname.container: "midas-runner-1"

volumes:
  nginx_conf:
  static:
  media:
  backup:
