version: '3.9'
services:
  midas:
    build:
      context: .
      network: host
      args: [ "DJANGO_SETTINGS_MODULE=MIDAS.settings.base" ]
    restart: unless-stopped
    volumes:
      - media:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=MIDAS.settings.base
      - admin_username=admin
      - admin_password=pw
      - admin_email=midas@midas.ch
    ports:
      - "8000:8000"

  runner:
    build:
      context: .
      network: host
      args: [ "DJANGO_SETTINGS_MODULE=MIDAS.settings.base" ]
    restart: "no"
    volumes:
      - media:/app/media
      - /home/amir/Git/MIDAS/docker/jobrunner.sh:/app/docker/jobrunner.sh
    command: bash /app/docker/jobrunner.sh

  scheduler:
    image: mcuadros/ofelia:latest
    depends_on:
      - midas
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.uname.schedule: "@every 5s"
      ofelia.job-run.uname.container: "midas-runner-1"

volumes:
  media:
