version: '3.9'
services:
  midas:
    build:
      context: .
      network: host
    ports:
      - "8000:8000"
    environment:
      - admin_username=admin
      - admin_password=pw
      - admin_email=midas@midas.ch
