openapi: 3.0.2
info:
  title: 'Routes'
  version: ''
paths:
  /api/status/:
    get:
      operationId: listStatus
      summary: 'Return the status of the website.'
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
          description: ''
      tags:
      - Status
  /api/status/third-party/:
    get:
      operationId: listStatusThirdPartys
      summary: 'Return the status of the websites used by GExplore, more precisely,
        if the sources of the website are all available, some, or none of them.'
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
          description: ''
      tags:
      - Status
  /api/sources/:
    get:
      operationId: listSources
      summary: List all Sources
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Source'
          description: ''
      tags:
      - Sources
  /api/sources/{id}/:
    get:
      operationId: retrieveSource
      summary: Retrieve a specific Source by the slug or the id
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this source.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Source'
          description: ''
      tags:
      - Sources
  /api/sources/{slug}/:
    get:
      operationId: retrieveSourceSlug
      summary: Retrieve a specific Source by the slug or the id
      parameters:
      - name: slug
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Source'
          description: ''
      tags:
      - Sources
  /api/stations/:
    get:
      operationId: listStations
      summary: List all Stations
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Station'
          description: ''
      tags:
      - Stations
  /api/stations/{id}/:
    get:
      operationId: retrieveStation
      summary: Retrieve a specific Station by the slug
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this station.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Station'
          description: ''
      tags:
      - Stations
  /api/stations/{slug}/:
    get:
      operationId: retrieveStationSlug
      summary: Retrieve a specific Station by the slug
      parameters:
      - name: slug
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Station'
          description: ''
      tags:
      - Stations
  /api/parameters/:
    get:
      operationId: listParameters
      summary: List all Parameters
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Parameter'
          description: ''
      tags:
      - Parameters
  /api/parameters/{id}/:
    get:
      operationId: retrieveParameter
      summary: Retrieve a specific Parameter by the slug  or the id
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this parameter.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Parameter'
          description: ''
      tags:
      - Parameters
  /api/parameters/{slug}/:
    get:
      operationId: retrieveParameterSlug
      summary: Retrieve a specific Parameter by the slug  or the id
      parameters:
      - name: slug
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Parameter'
          description: ''
      tags:
      - Parameters
  /api/favorites-group/:
    get:
      operationId: listGroupOfFavorites
      summary: List all Parameters
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FavoriteGroup'
          description: ''
      tags:
      - Favorites
  /api/favorites-group/{id}/:
    get:
      operationId: retrieveGroupOfFavorite
      summary: Retrieve a specific Parameter by the slug  or the id
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this group of favorite.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FavoriteGroup'
          description: ''
      tags:
      - Favorites
  /api/favorites-group/{slug}/:
    get:
      operationId: retrieveGroupOfFavoriteSlug
      summary: Retrieve a specific Parameter by the slug  or the id
      parameters:
      - name: slug
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FavoriteGroup'
          description: ''
      tags:
      - Favorites
  /api/filter/:
    post:
      operationId: createFilter
      summary: "Filter data. If stations, filter params, if sources, filter stations"
      parameters: []
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - Filter
  /api/search/:
    post:
      operationId: createSearch
      summary: "Search datas in files"
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - Search
components:
  schemas:
    Status:
      type: object
      properties:
        status:
          type: string
          readOnly: true
    Source:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        slug:
          type: string
          readOnly: true
        url:
          type: string
          format: uri
          maxLength: 200
          pattern: "^(?:[a-z0-9.+-]*)://(?:[^\\s:@/]+(?::[^\\s:@/]*)?@)?(?:(?:0|25[0-5]|2[0-4]\\\
            d|1\\d?\\d?|[1-9]\\d?)(?:\\.(?:0|25[0-5]|2[0-4]\\d|1\\d?\\d?|[1-9]\\d?)){3}|\\\
            [[0-9a-f:.]+\\]|([a-z\xA1-\uFFFF0-9](?:[a-z\xA1-\uFFFF0-9-]{0,61}[a-z\xA1\
            -\uFFFF0-9])?(?:\\.(?!-)[a-z\xA1-\uFFFF0-9-]{1,63}(?<!-))*\\.(?!-)(?:[a-z\xA1\
            -\uFFFF-]{2,63}|xn--[a-z0-9]{1,59})(?<!-)\\.?|localhost))(?::\\d{1,5})?(?:[/?#][^\\\
            s]*)?\\z"
        infos:
          type: string
          maxLength: 500
        station:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                readOnly: true
              name:
                type: string
                maxLength: 255
              slug:
                type: string
                readOnly: true
      required:
      - station
    Station:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        slug:
          type: string
          readOnly: true
        source:
          type: object
          properties:
            name:
              type: string
              maxLength: 255
            slug:
              type: string
              readOnly: true
        infos:
          type: string
          maxLength: 500
        latitude:
          type: string
          format: decimal
          multipleOf: 1.0e-15
          maximum: 1000000000000000
          minimum: -1000000000000000
          nullable: true
        longitude:
          type: string
          format: decimal
          multipleOf: 1.0e-15
          maximum: 1000000000000000
          minimum: -1000000000000000
          nullable: true
        height:
          type: string
          format: decimal
          multipleOf: 1.0e-05
          maximum: 100000
          minimum: -100000
          nullable: true
          description: Height in meters
        parameters_list:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                readOnly: true
              slug:
                type: string
                readOnly: true
              infos:
                type: string
                readOnly: true
      required:
      - source
      - Parameters_list
    Parameter:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        slug:
          type: string
          readOnly: true
        infos:
          type: string
          maxLength: 500
    FavoriteGroup:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
        slug:
          type: string
          readOnly: true
        user:
          type: string
          readOnly: true
        favorites_list:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                readOnly: true
              parameters_of_station:
                type: array
                items:
                  type: object
                  properties:
                    station:
                      type: string
                      readOnly: true
                    parameter:
                      type: string
                      readOnly: true
            required:
            - Parameters_of_station
      required:
      - Favorites_list
